[Admin] Add a link on the IP modal to search for a given IP address accross all users.
CTFd/CTFd pull request #2113
Opened 2022-05-06 15:18 UTC by Cryptanalyse

Add the possibility to click on a user IP on the admin to search for this IP, as if if were entered in the search field.

2022-05-06 20:08 UTC, ColdHeat requested changes
If you can make this change I will merge

2022-05-06 20:08 UTC, ColdHeat commented on CTFd/themes/admin/templates/modals/users/addresses.html
> +						<a href="{{ url_for('admin.view') }}/users?field=ip&q={{ addr.ip }}">
You should be able to do this entirely with a url_for call. Something like `url_for('admin.users', field='ip', q=addr.ip)`.

2022-05-06 20:45 UTC, Cryptanalyse commented
Done! Indeed, this is cleaner, thanks!

2022-05-08 06:56 UTC, merged

2022-05-08 06:57 UTC, ColdHeat commented
Made a few other changes but thanks for adding this I think it is a good feature.